name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
       
    - name: build sender
      run: g++ -Wall -Wextra -o testsender TestSender.cpp BMS_Sender.c
  
    - name: Run Sender
      run: ./testsender
      
    - name: collect Sender coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: create Sender coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage_sender
        path: ./*.html
        retention-days: 21
      
    - name: Run and collect Receiver coverage
      run: |
        coverage run --branch receiver_test.py
        coverage html
        coverage report
          
    - name: Upload Receiver coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage_receiver
        path: ./htmlcov
        retention-days: 21
      
    - name: Pipeline Sender and receiver
      run: ./testsender | python receiver.py
